### ISSUE TITLE
EnumMap is missing get_mut

### ISSUE THREAD

**Issue by taladar** [komadori/enumoid#1]
While trying to use EnumMap to store counts per enum value I noticed that it is missing a get_mut method which I assume is an oversight considering it has other ways to access values mutably.

**Comment by komadori** [comment]
I agree. I will add `get_mut` to `EnumMap`, `EnumOptionMap`, and `EnumVec`.

**Comment by komadori** [comment]
Fixed in 0.2.2.

**Comment by taladar** [comment]
Thanks
